---
title: "NYC Restaurant Inspections"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: 
      version: 4
      bootswatch: lumen
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

```{r}
data("rest_inspec")

nyc_rest = 
  rest_inspec |> 
  mutate (
    inspection_date = as.Date(inspection_date, format = "%Y-%m-%d")
  ) |> 
  filter(
    boro == "Manhattan",
    inspection_date >= "2019-01-01"
  )
```


Column {data-width=650}
-----------------------------------------------------------------------

### Map of Restaurants by Grade

```{r}
nyc_rest |>
  filter(latitude != 0, longitude != 0, !is.na(grade)) |> 
  distinct(camis, dba, cuisine_description, latitude, longitude, grade) |> 
  mutate(
    text_label = str_c("Name: ", dba, "\nCuisine: ", cuisine_description, "\nGrade: ", grade)
    ) |> 
  plot_ly(
    x = ~longitude, y = ~latitude, type = "scatter", mode = "markers",
    color = ~grade, text = ~text_label, alpha = 0.5, colors = "viridis")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Number of Restaurants by Cuisine

```{r}
nyc_rest |> 
  distinct(camis, dba, cuisine_description) |> 
  count(cuisine_description) |> 
  mutate(
    cuisine_description = fct_reorder(cuisine_description, n)
    ) |> 
  plot_ly(y = ~cuisine_description, x = ~n, color = ~cuisine_description, type = "bar", colors = "viridis") |> 
  layout(showlegend = FALSE)
```

### Scores of Most popular Cuisines

```{r}
nyc_rest |> 
  filter(cuisine_description %in% c("American", "Italian", "Chinese", "Japanese", "Mexican", "Pizza", "French", "Indian", "Thai")) |> 
  plot_ly(x = ~cuisine_description, y = ~score, color = ~cuisine_description, type = "box", colors = "viridis")
```

